### ISSUE TITLE
[Release Issue] Deploy step not executed

### ISSUE THREAD

**Issue by vphilippon** [jazzband/pip-tools#716]
The current Travis configuration (I think) did not trigger the deployement to jazzband pypi server.

https://travis-ci.org/jazzband/pip-tools/jobs/483642337

@atugushev @jezdez Any idea of recent change that may be in cause?

**Comment by atugushev** [comment]
@vphilippon 
The issue is in `after_success: skip`. There should be `after_success: true`. See for details https://github.com/travis-ci/travis-ci/issues/8337. I've prepared a PR to fix that.

**Comment by SpotlightKid** [comment]
I'm not sure if this related, but the latest release (3.3.0) apparently hasn't been uploaded to PyPI yet as well.

**Comment by atugushev** [comment]
Hello @SpotlightKid,

That's right. I believe the release will be uploaded as soon as closed current issue.

**Comment by vphilippon** [comment]
I'll be making a 3.3.1 release (with the pipeline fixed) during the day).

**Comment by vphilippon** [comment]
Done: https://pypi.org/project/pip-tools/3.3.1/

Thanks @atugushev for the prompt help & fix!

**Comment by SpotlightKid** [comment]
Cool. [AUR package](https://aur.archlinux.org/packages/pip-tools/) updated.

**Comment by SpotlightKid** [comment]
This seems to have happened again. Was notified about a release on Github yesterday, still do not see the release on PyPI.

**Comment by atugushev** [comment]
@SpotlightKid package has been uploaded successfully, but release not approved yet, see https://github.com/jazzband/roadies/issues/141.

**Comment by SpotlightKid** [comment]
Ah, I see.

**Comment by atugushev** [comment]
@SpotlightKid FYI 3.6.0 is released
